name: phasm
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - python>=3.5
    - numpy
    - scipy
    - pandas
    - matplotlib
    - seaborn
    - networkx<2
    - jupyter
    - ipython
    - samtools
    - pytest
    - snakemake>=3.11
    - dazz_db=1.0p1
    - daligner=1.0p1
    - pip:
        - pysam
        - pybedtools
        - simlord
        - intervaltree
        - matplotlib-venn
