name: phasm
channels:
    - bioconda
dependencies:
    - python>=3.5
    - numpy
    - scipy
    - pandas
    - matplotlib
    - seaborn
    - networkx
    - jupyter
    - ipython
    - samtools
    - pytest
    - snakemake>=3.10
    - dazz_db=1.0p1
    - daligner=1.0p1
    - pip:
        - pysam
        - pybedtools
        - simlord
